[profile.default]
solc = "0.8.29"
optimizer = true
optimizer_runs = 10_000
evm_version = "cancun"
src = "contracts"
out = "foundry-artifacts"
cache_path = "cache/foundry"
test = "test/foundry"

libs = ["node_modules"]
allow_paths = ["node_modules"]

remappings = [
    "forge-std/=node_modules/forge-std/",
    "contracts/=contracts/",
]

[profile.prod]
via_ir = true

[fmt]
tab_width = 4
line_length = 120
multiline_func_header = "params_first_multi"
single_line_statement_blocks = "preserve"
prefer_compact = "none"
single_line_imports = true
bracket_spacing = true
sort_imports = true
int_types = "short"