require("./deployBase");
require("./deployModule");
require("./enterProtocol");
require("./grantBackendRoles");
require("./changeAdmin");
require("./deployRegistry");
require("./deployModuleImplementation");
require("./upgradeModuleImplementation");
require("./getEffectiveBalance");
